### ISSUE TITLE
Outils Editeur de figure Smalltalk

### ISSUE THREAD

**Issue by cstes** [hilaire/drgeo#23]
In the blog article

https://gnu-drgeo.blogspot.com/2023/10/programmer-geometrie-lecon-1.html#more

it is written that "from DrGeo , it should be possible to click in the window and select from a menu Outils -> Editeur de figure Smalltalk.

I don't see this menu.   I am able to draw figures like the triangle from the blog article using the DrGSmalltalkSketchBrowser or DrGSmalltalkSketchEditor or even in the Cuis global window.

The strategy to use : sketch point: 0@0.  sketch view openInWorld 

that works.  It opens and draws the DrGeoFigure in the Cuis global window.

However if I use 

DrGeo new

I get a different window and I don't see how to use a menu Outils -> Editeur de figure Smalltalk from there

The only way to get the DrGSmalltalkSketchEditor

seems to be to send a open: label: message to it which works.

Is there a way to draw the sketch please in the window created by DrGeo new ?

**Comment by hilaire** [comment]
It is because you are using DrGeo in its development environment, which is fine. In that circumstance, the World menu is the one from Cuis.
If you want to test the DrGeo world menu from the development environment, you can execute "DrGeoSystem beWorkstation". To get back to Cuis world menu, execute "DrGeoSystem beDevelopment"
